"""One-way, replayable import of the recipes Grocy still holds.

Reads a read-only copy of grocy.db. Nothing is written without apply=True —
and `apply` governs BOTH the SQL writes and the file writes: a dry run that
still wrote 6.5 MB of images would be a disguised write, and the SQL rollback
does not cover the disk.

ONE transaction, and only one. `Database._lock` is NOT reentrant: two nested
`db.write()` freeze the process without raising. Every helper takes `conn`.

**The amendment to lot 3 § 18, and it is the most important line here.** Lot 3
writes that the 15 type-`1` recipes "are the phantom copies". That is false.
They are 15 real recipes, created on 2026-06-27 between 18:45 and 18:55 by a
tool that wrote `type = 1` instead of `type = 'normal'` — Salade de lentilles
fraîche, Bowl protéiné fromage blanc, Taboulé quinoa été. They carry 96
ingredient rows and 10 meal-plan entries point at them. A strict
`WHERE type = 'normal'`, exactly as lot 3 prescribes, would lose 15 recipes
and 96 rows IN SILENCE.

The 166 real phantoms (86 `mealplan-shadow`, 65 `mealplan-day`, 15
`mealplan-week`) are left out by the same filter: they all carry NEGATIVE ids
and are generated by the `meal_plan` triggers.

Grocy's recipe-nesting table is never read — 5 651 rows, nearly all produced
by those same triggers, no real use ever observed (lot 3 § 20). Its name is
deliberately not written here: a test scans this module's source for it, and a
mention in a comment would make that scan lie.
"""
from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Mapping

from .const import GROCY_RECIPE_REF_PREFIX
from .grocy import html as gh
from .grocy import pictures as gp
from .storage import repositories as repo

# Le filtre. `IN ('normal', '1')`, jamais `= 'normal'`.
GROCY_RECIPE_TYPES = ("normal", "1")

# Les 17 recettes réécrites le 2026-08-18 : le README de grocy-off dit que
# leurs étapes, leurs titres, leurs durées de minuteur et leurs ustensiles sont
# INVENTÉS. C'est exactement ce que `needs_review` veut dire.
REWRITTEN_RECIPES = frozenset(
    {41, *range(43, 51), *range(96, 104)})

RECIPE_PICTURE_DIR = "recipes"
# Le dossier tel que media_source le nomme, à partir de la racine de media/.
RECIPE_MEDIA_DIR = "home_stock/recipes"


class RecipeImportError(Exception):
    """Something the import refuses to guess about."""


@dataclass
class RecipeReport:
    """What was written, and what must be looked at by hand."""

    recipes: int = 0
    steps: int = 0
    instructions: int = 0
    ingredients: int = 0
    pictures: int = 0
    meals: int = 0
    unmatched: int = 0
    skipped: int = 0
    anomalies: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.anomalies

    def as_dict(self) -> dict[str, Any]:
        return {
            "recipes": self.recipes, "steps": self.steps,
            "instructions": self.instructions, "ingredients": self.ingredients,
            "pictures": self.pictures, "meals": self.meals,
            "unmatched": self.unmatched, "skipped": self.skipped,
            "anomalies": self.anomalies, "ok": self.ok,
        }


def _open_grocy(path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def _grocy_recipes(grocy) -> list[dict[str, Any]]:
    """The 102 recipes. `rec` for recipes — never `b`."""
    marques = ", ".join("?" * len(GROCY_RECIPE_TYPES))
    return [dict(row) for row in grocy.execute(
        "SELECT rec.id AS id, rec.name AS name, rec.description AS description,"
        "       rec.base_servings AS base_servings, rec.type AS type"
        f" FROM recipes AS rec WHERE rec.type IN ({marques}) ORDER BY rec.id",
        GROCY_RECIPE_TYPES)]


def _write_pictures(recipe_id: int, description: str, picture_dir: Path,
                    report: RecipeReport, *, apply: bool) -> dict[str, str]:
    """Bring home what dies with the container, and only that.

    The 62 data-URIs are decoded here — that data is in the database we are
    already reading. The 55 hosted files are only RENAMED into a media id: the
    Home Assistant container cannot see Grocy's storage folder, so copying
    them is gesture 3, done by the owner.

    The 112 Unsplash references get no entry in the mapping at all, so
    `reecrire` leaves them byte for byte.
    """
    mapping: dict[str, str] = {}
    rang = 0
    for reference in gp.references(description):
        if reference.family == "external":
            continue
        if reference.family == "grocy":
            mapping[reference.src] = gp.media_id(RECIPE_MEDIA_DIR,
                                                 reference.filename)
            continue
        nom = gp.nom_inline(recipe_id, rang)
        rang += 1
        mapping[reference.src] = gp.media_id(RECIPE_MEDIA_DIR, nom)
        report.pictures += 1
        if apply:
            # Déterministe : le rejeu réécrit le MÊME fichier au lieu d'en
            # accumuler un nouveau par passage.
            gp.ecrire_inline(reference.src, str(picture_dir / nom))
    return mapping


def _import_recipe_within(conn, ligne: Mapping[str, Any], picture_dir: Path,
                          report: RecipeReport, *, apply: bool) -> int | None:
    """One recipe, its pages and its bullets. Returns the home_stock id."""
    source_ref = str(ligne["id"])
    existante = repo.find_recipe_by_source(conn, "grocy", source_ref)
    if existante is not None:
        report.skipped += 1
        return existante["id"]

    description = ligne["description"] or ""
    mapping = _write_pictures(ligne["id"], description, picture_dir, report,
                              apply=apply)
    description = gp.reecrire(description, mapping)

    pages = gh.decouper(description)
    meta = gh.meta(description)
    couverture = next((p for p in pages if p.kind == "cover"), None)

    report.recipes += 1
    # Les pages, toutes sauf le bloc « Ingrédients » : il est un RENDU de
    # recipes_pos, jamais une source. La réimporter serait la deuxième
    # écriture d'une même quantité.
    a_ecrire = [p for p in pages if p.kind != "ingredients"]
    report.steps += len(a_ecrire)
    for page in a_ecrire:
        for puce in page.bullets:
            report.instructions += len(gh.instructions(puce))
    if not apply:
        return None

    recipe_id = repo.insert_recipe(
        conn, name=ligne["name"], source="grocy", source_ref=source_ref,
        created_at=_now(), servings=int(ligne["base_servings"] or 1),
        total_minutes=meta.total_minutes, utensils=meta.utensils,
        summary=meta.summary,
        image_url=couverture.images[0] if couverture and couverture.images else None,
        needs_review=1 if ligne["id"] in REWRITTEN_RECIPES else 0,
        external_ref=f"{GROCY_RECIPE_REF_PREFIX}{ligne['id']}",
    )
    for position, page in enumerate(a_ecrire, start=1):
        step_id = repo.insert_step(
            conn, recipe_id=recipe_id, position=position, title=page.title,
            image_url=page.images[0] if page.images else None)
        rang = 0
        for puce in page.bullets:
            for instruction in gh.instructions(puce):
                rang += 1
                repo.insert_instruction(
                    conn, step_id=step_id, position=rang,
                    text=instruction.text or instruction.timer_label or "—",
                    timer_label=instruction.timer_label,
                    timer_seconds=instruction.timer_seconds)
    return recipe_id


def import_recipes(db, grocy_path: str, *, picture_dir, apply: bool = False,
                   today: str | None = None) -> RecipeReport:
    """Bring recipes, pictures and the meal plan over. Dry run by default."""
    report = RecipeReport()
    dossier = Path(picture_dir) / RECIPE_PICTURE_DIR
    if apply:
        dossier.mkdir(parents=True, exist_ok=True)
    grocy = _open_grocy(grocy_path)
    try:
        with db.write() as conn:            # UNE transaction, et une seule
            for ligne in _grocy_recipes(grocy):
                _import_recipe_within(conn, ligne, dossier, report, apply=apply)
            if not apply:
                conn.rollback()
    finally:
        grocy.close()
    return report
