"""One-way, replayable import of the recipes Grocy still holds.

Reads a read-only copy of grocy.db. Nothing is written without apply=True —
and `apply` governs BOTH the SQL writes and the file writes: a dry run that
still wrote 6.5 MB of images would be a disguised write, and the SQL rollback
does not cover the disk.

ONE transaction, and only one. `Database._lock` is NOT reentrant: two nested
`db.write()` freeze the process without raising. Every helper takes `conn`.

**The amendment to lot 3 § 18, and it is the most important line here.** Lot 3
writes that the 15 type-`1` recipes "are the phantom copies". That is false.
They are 15 real recipes, created on 2026-06-27 between 18:45 and 18:55 by a
tool that wrote `type = 1` instead of `type = 'normal'` — Salade de lentilles
fraîche, Bowl protéiné fromage blanc, Taboulé quinoa été. They carry 96
ingredient rows and 10 meal-plan entries point at them. A strict
`WHERE type = 'normal'`, exactly as lot 3 prescribes, would lose 15 recipes
and 96 rows IN SILENCE.

The 166 real phantoms (86 `mealplan-shadow`, 65 `mealplan-day`, 15
`mealplan-week`) are left out by the same filter: they all carry NEGATIVE ids
and are generated by the `meal_plan` triggers.

Grocy's recipe-nesting table is never read — 5 651 rows, nearly all produced
by those same triggers, no real use ever observed (lot 3 § 20). Its name is
deliberately not written here: a test scans this module's source for it, and a
mention in a comment would make that scan lie.
"""
from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Mapping

from .const import GROCY_MEAL_UID_TEMPLATE, GROCY_RECIPE_REF_PREFIX
from .grocy import html as gh
from .grocy import pictures as gp
from .grocy.units import base_unit
from .storage import repositories as repo

# Le filtre. `IN ('normal', '1')`, jamais `= 'normal'`.
GROCY_RECIPE_TYPES = ("normal", "1")

# Les 17 recettes réécrites le 2026-08-18 : le README de grocy-off dit que
# leurs étapes, leurs titres, leurs durées de minuteur et leurs ustensiles sont
# INVENTÉS. C'est exactement ce que `needs_review` veut dire.
REWRITTEN_RECIPES = frozenset(
    {41, *range(43, 51), *range(96, 104)})

RECIPE_PICTURE_DIR = "recipes"
# Le dossier tel que media_source le nomme, à partir de la racine de media/.
RECIPE_MEDIA_DIR = "home_stock/recipes"


class RecipeImportError(Exception):
    """Something the import refuses to guess about."""


@dataclass
class RecipeReport:
    """What was written, and what must be looked at by hand."""

    recipes: int = 0
    steps: int = 0
    instructions: int = 0
    ingredients: int = 0
    pictures: int = 0
    meals: int = 0
    unmatched: int = 0
    skipped: int = 0
    anomalies: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.anomalies

    def as_dict(self) -> dict[str, Any]:
        return {
            "recipes": self.recipes, "steps": self.steps,
            "instructions": self.instructions, "ingredients": self.ingredients,
            "pictures": self.pictures, "meals": self.meals,
            "unmatched": self.unmatched, "skipped": self.skipped,
            "anomalies": self.anomalies, "ok": self.ok,
        }


def _open_grocy(path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def _today() -> str:
    return datetime.now(UTC).date().isoformat()


def _grocy_recipes(grocy) -> list[dict[str, Any]]:
    """The 102 recipes. `rec` for recipes — never `b`."""
    marques = ", ".join("?" * len(GROCY_RECIPE_TYPES))
    return [dict(row) for row in grocy.execute(
        "SELECT rec.id AS id, rec.name AS name, rec.description AS description,"
        "       rec.base_servings AS base_servings, rec.type AS type"
        f" FROM recipes AS rec WHERE rec.type IN ({marques}) ORDER BY rec.id",
        GROCY_RECIPE_TYPES)]


def _write_pictures(recipe_id: int, description: str, picture_dir: Path,
                    report: RecipeReport, *, apply: bool) -> dict[str, str]:
    """Bring home what dies with the container, and only that.

    The 62 data-URIs are decoded here — that data is in the database we are
    already reading. The 55 hosted files are only RENAMED into a media id: the
    Home Assistant container cannot see Grocy's storage folder, so copying
    them is gesture 3, done by the owner.

    The 112 Unsplash references get no entry in the mapping at all, so
    `reecrire` leaves them byte for byte.
    """
    mapping: dict[str, str] = {}
    rang = 0
    for reference in gp.references(description):
        if reference.family == "external":
            continue
        if reference.family == "grocy":
            mapping[reference.src] = gp.media_id(RECIPE_MEDIA_DIR,
                                                 reference.filename)
            continue
        if reference.src in mapping:
            # La MÊME charge utile revient sur plusieurs pages d'une recette :
            # 62 occurrences pour 27 images réelles. Lui donner un nom par
            # occurrence écrirait 62 fichiers dont 35 que plus rien ne
            # référencerait — et un fichier que personne ne référence est
            # exactement ce que C9 signale comme orphelin.
            continue
        nom = gp.nom_inline(recipe_id, rang)
        rang += 1
        mapping[reference.src] = gp.media_id(RECIPE_MEDIA_DIR, nom)
        report.pictures += 1
        if apply:
            # Déterministe : le rejeu réécrit le MÊME fichier au lieu d'en
            # accumuler un nouveau par passage.
            gp.ecrire_inline(reference.src, str(picture_dir / nom))
    return mapping


def _import_recipe_within(conn, ligne: Mapping[str, Any], picture_dir: Path,
                          report: RecipeReport, *, apply: bool) -> int | None:
    """One recipe, its pages and its bullets. Returns the home_stock id."""
    source_ref = str(ligne["id"])
    if repo.find_recipe_by_source(conn, "grocy", source_ref) is not None:
        # Rien n'est réécrit, et surtout pas ses ingrédients : une ligne
        # arbitrée à la main sur l'écran d'appariement ne se fait pas effacer
        # par un second passage. Le rejeu importe ce qui manque, pas ce qui
        # est déjà là.
        report.skipped += 1
        return None

    description = ligne["description"] or ""
    mapping = _write_pictures(ligne["id"], description, picture_dir, report,
                              apply=apply)
    description = gp.reecrire(description, mapping)

    pages = gh.decouper(description)
    meta = gh.meta(description)
    couverture = next((p for p in pages if p.kind == "cover"), None)

    report.recipes += 1
    # Les pages, toutes sauf le bloc « Ingrédients » : il est un RENDU de
    # recipes_pos, jamais une source. La réimporter serait la deuxième
    # écriture d'une même quantité.
    a_ecrire = [p for p in pages if p.kind != "ingredients"]
    report.steps += len(a_ecrire)
    for page in a_ecrire:
        for puce in page.bullets:
            report.instructions += len(gh.instructions(puce))
    if not apply:
        return None

    recipe_id = repo.insert_recipe(
        conn, name=ligne["name"], source="grocy", source_ref=source_ref,
        created_at=_now(), servings=int(ligne["base_servings"] or 1),
        total_minutes=meta.total_minutes, utensils=meta.utensils,
        summary=meta.summary,
        image_url=couverture.images[0] if couverture and couverture.images else None,
        needs_review=1 if ligne["id"] in REWRITTEN_RECIPES else 0,
        external_ref=f"{GROCY_RECIPE_REF_PREFIX}{ligne['id']}",
    )
    for position, page in enumerate(a_ecrire, start=1):
        step_id = repo.insert_step(
            conn, recipe_id=recipe_id, position=position, title=page.title,
            image_url=page.images[0] if page.images else None)
        rang = 0
        for puce in page.bullets:
            for instruction in gh.instructions(puce):
                rang += 1
                repo.insert_instruction(
                    conn, step_id=step_id, position=rang,
                    text=instruction.text or instruction.timer_label or "—",
                    timer_label=instruction.timer_label,
                    timer_seconds=instruction.timer_seconds)
    return recipe_id


def _import_ingredients_within(conn, grocy, recipe_ids: Mapping[int, int],
                               report: RecipeReport, *, apply: bool) -> None:
    """The 510 ingredient rows, 25 of which are left for a human to sign.

    The product is resolved by `product.external_ref`, NEVER by name. On the
    414 rows of the 87 `normal` recipes: 0 row without a product, 0 row
    pointing at an inactive product, 0 row whose `qu_id` differs from its
    product's `qu_id_stock`. On the 96 rows of the 15 type-`1` recipes it is
    another story: 23 rows carry a diverging unit and 2 point at an inactive
    product.

    The 23 are the defect grocy-off's README describes — "42 rows carried the
    packaging unit (`1.5 Bouteille` of olive oil) while the number was already
    in cl" — never fixed on these fifteen, because `recettes_ingredients.py`
    filters on `type = 'normal'`. **Eleven say "1 Bouteille" of olive oil when
    `variable_amount` says "1 cs"**: imported as they are, they would take 750
    ml of oil for a tablespoon, AT EVERY VALIDATED MEAL.

    Such a row comes in with `amount = NULL`, its product resolved,
    `match_state = 'unmatched'`, `raw_text = variable_amount`, and is named in
    the report.

    **`variable_amount` is never parsed back into a quantity.** "1 cs" would
    resolve against the culinary measures seeded by m004. Refused: lot 3 § 18,
    `variable_amount` is provenance, "it does not come back through the back
    door". Twenty-five rows are fixed by hand in ten minutes on lot 3's
    matching screen; a parser would be fixed for years.

    The other 485 are `confirmed`, not `auto`: lot 3 reserves `auto` for a
    GUESSED, scored match. Here nothing is guessed — the product comes from an
    id. `match_score` stays NULL: writing 1.0 would suggest an algorithm was
    very sure of itself.
    """
    unites = {row["id"]: row["name"] for row in
              grocy.execute("SELECT id, name FROM quantity_units")}
    produits = {}
    for row in conn.execute(
        "SELECT prod.id AS id, prod.external_ref AS ref, prod.name AS name,"
        "       prod.base_unit AS base_unit"
        " FROM product AS prod WHERE prod.external_ref IS NOT NULL"
    ):
        produits[int(row["ref"])] = row

    stock_units = {row["id"]: row["qu_id_stock"] for row in
                   grocy.execute("SELECT id, qu_id_stock FROM products")}
    hors_stock = 0
    positions: dict[int, int] = {}
    for ligne in grocy.execute(
        "SELECT pos.id AS id, pos.recipe_id AS recipe_id,"
        "       pos.product_id AS product_id, pos.amount AS amount,"
        "       pos.qu_id AS qu_id, pos.variable_amount AS variable_amount,"
        "       pos.ingredient_group AS ingredient_group,"
        "       pos.not_check_stock_fulfillment AS not_check_stock_fulfillment,"
        "       rec.name AS recipe_name, prod.name AS grocy_product_name"
        " FROM recipes_pos AS pos"
        " JOIN recipes AS rec ON rec.id = pos.recipe_id"
        " LEFT JOIN products AS prod ON prod.id = pos.product_id"
        " ORDER BY pos.id"
    ):
        recipe_id = recipe_ids.get(ligne["recipe_id"])
        if recipe_id is None:
            continue                   # les 200 orphelines, et les fantômes
        if ligne["not_check_stock_fulfillment"]:
            hors_stock += 1

        produit = produits.get(ligne["product_id"])
        unite = unites.get(ligne["qu_id"])
        mappee = base_unit(unite) if unite else None
        # La comparaison porte sur le qu_id, PAS sur l'unité de base résolue :
        # « 1 Pièce » de roquette stockée en « Sachet » donne piece des deux
        # côtés, et la source dit « 1 poignée ». Deux unités de conditionnement
        # différentes ne disent pas la même chose parce qu'elles se résolvent
        # au même mot.
        meme_unite = (produit is not None
                      and ligne["qu_id"] == stock_units.get(ligne["product_id"]))
        raw_text = ligne["variable_amount"] or (
            f"{_nombre(ligne['amount'])} {unite}" if unite
            else _nombre(ligne["amount"]))

        if produit is None:
            nom_grocy = (ligne["grocy_product_name"]
                         or f"produit Grocy {ligne['product_id']}")
            report.unmatched += 1
            report.anomalies.append(
                f"{ligne['recipe_name']} / {nom_grocy}"
                " : absent du catalogue de home_stock (désactivé chez Grocy),"
                f" quantité laissée vide — la source dit « {raw_text} ». Le"
                " produit actif équivalent ne peut être signé que par un"
                " humain, sur l'écran d'appariement du lot 3")
            etat, amount, product_id = "unmatched", None, None
        elif mappee is None or not meme_unite or mappee[0] != produit["base_unit"]:
            report.unmatched += 1
            report.anomalies.append(
                f"{ligne['recipe_name']} / {produit['name']} : unité"
                f" « {unite} » alors que le produit est stocké en"
                f" « {produit['base_unit']} » — {_nombre(ligne['amount'])}"
                f" {unite}, la source dit « {raw_text} ». Quantité laissée"
                " vide, à trancher à la main")
            etat, amount, product_id = "unmatched", None, produit["id"]
        else:
            etat = "confirmed"
            amount = (ligne["amount"] or 0) * mappee[1]
            product_id = produit["id"]

        report.ingredients += 1
        if not apply:
            continue
        positions[recipe_id] = positions.get(recipe_id, 0) + 1
        repo.insert_ingredient(
            conn, recipe_id=recipe_id, position=positions[recipe_id],
            raw_text=raw_text, product_id=product_id, amount=amount,
            group_name=ligne["ingredient_group"] or None,
            match_state=etat, external_ref=str(ligne["id"]))

    if hors_stock:
        # Aucune colonne équivalente, et sans effet : valider un repas vérifie
        # le stock de toute façon. Mentionné une fois, avec son compte.
        report.anomalies.append(
            f"{hors_stock} lignes d'ingrédient marquées « hors stock » chez"
            " Grocy : l'indication n'est pas reprise, la validation d'un repas"
            " vérifie le stock de toute façon")


# Les sections de Grocy vers les créneaux de m004. La ligne `id = -1` — le
# « sans section » de Grocy, que m004 n'a pas semée — n'y est PAS : les 30
# entrées qui l'utilisent sont toutes dans le passé, et la décision de ne
# reprendre que l'avenir referme ce problème d'elle-même.
GROCY_SECTION_TO_SLOT = {1: "breakfast", 2: "lunch", 3: "dinner"}


def _import_meal_plan_within(conn, grocy, recipe_ids: Mapping[int, int],
                             report: RecipeReport, *, today: str,
                             apply: bool) -> None:
    """The 42 entries ahead. The 66 behind are dropped, and neither middle
    ground works:

    - importing them `state = 'done'` would assert validated meals — and
      validating a meal WRITES movements (lot 3), of which there would be
      none behind. A `done` meal with no movement is a lie in a database
      whose journal is the only source of truth;
    - importing them `planned` would fill the calendar with 66 meals to cook
      in the past, and `sensor.home_stock_next_meal` would go looking for
      them.

    `today` is a PARAMETER, never a literal: the target moves, and "ahead" is
    computed on switchover day.
    """
    connues = {row["source_ref"]: row["id"] for row in conn.execute(
        "SELECT source_ref, id FROM recipe WHERE source = 'grocy'"
        "   AND source_ref IS NOT NULL")}
    connues.update({str(gid): interne for gid, interne in recipe_ids.items()
                    if interne is not None})
    # En simulation rien n'est inséré, donc rien n'a d'identifiant interne :
    # la résolvabilité se juge sur les recettes VUES, et le rapport compte
    # exactement ce qu'un vrai passage écrirait.
    resolvables = set(connues) | {str(gid) for gid in recipe_ids}
    deja = {row["uid"] for row in conn.execute("SELECT uid FROM meal")}
    maintenant = _now()

    for ligne in grocy.execute(
        "SELECT plan.id AS id, plan.day AS day, plan.type AS type,"
        "       plan.recipe_id AS recipe_id,"
        "       plan.recipe_servings AS recipe_servings, plan.note AS note,"
        "       plan.section_id AS section_id"
        " FROM meal_plan AS plan WHERE plan.day >= ? ORDER BY plan.id",
        (today,)
    ):
        uid = GROCY_MEAL_UID_TEMPLATE.format(id=ligne["id"])
        slot = GROCY_SECTION_TO_SLOT.get(ligne["section_id"])
        if slot is None:
            report.anomalies.append(
                f"planning du {ligne['day']} : section Grocy"
                f" {ligne['section_id']} sans créneau correspondant, entrée"
                " ignorée")
            continue

        recipe_id = None
        if ligne["type"] == "recipe":
            if str(ligne["recipe_id"]) not in resolvables:
                # Le planning se réimporte en dix secondes ; une entrée
                # orpheline se découvre au dîner.
                raise RecipeImportError(
                    f"planning du {ligne['day']} : la recette"
                    f" {ligne['recipe_id']} n'a pas été importée")
            recipe_id = connues.get(str(ligne["recipe_id"]))

        note = ligne["note"] or None
        est_recette = ligne["type"] == "recipe"
        if est_recette and note:
            # meal impose « une recette OU un produit OU une note, jamais
            # deux ». La recette gagne, et la note est RAPPORTÉE plutôt
            # qu'avalée : c'est une phrase que quelqu'un a écrite.
            report.anomalies.append(
                f"planning du {ligne['day']} : la note « {note} » accompagne"
                " une recette et n'a pas de colonne où aller — meal n'accepte"
                " qu'une recette OU une note")
            note = None
        if not est_recette and not note:
            report.anomalies.append(
                f"planning du {ligne['day']} : entrée sans recette ni note,"
                " ignorée")
            continue

        report.meals += 1
        if not apply or uid in deja:
            continue
        deja.add(uid)
        repo.insert_meal(
            conn, uid=uid, day=ligne["day"], slot_key=slot,
            created_at=maintenant, recipe_id=recipe_id, note=note,
            servings=ligne["recipe_servings"] or 1,
            external_ref=str(ligne["id"]))


def _nombre(valeur) -> str:
    """« 500 » et non « 500.0 » : raw_text est ce que la source disait."""
    if valeur is None:
        return ""
    entier = int(valeur)
    return str(entier) if valeur == entier else str(valeur)


def import_recipes(db, grocy_path: str, *, picture_dir, apply: bool = False,
                   today: str | None = None) -> RecipeReport:
    """Bring recipes, pictures and the meal plan over. Dry run by default."""
    report = RecipeReport()
    dossier = Path(picture_dir) / RECIPE_PICTURE_DIR
    if apply:
        dossier.mkdir(parents=True, exist_ok=True)
    grocy = _open_grocy(grocy_path)
    try:
        with db.write() as conn:            # UNE transaction, et une seule
            recipe_ids: dict[int, int | None] = {}
            for ligne in _grocy_recipes(grocy):
                # Toutes les recettes VUES, pas seulement celles écrites :
                # en simulation il n'y a pas d'identifiant interne, et le
                # planning doit quand même pouvoir dire si sa recette existe.
                recipe_ids[ligne["id"]] = _import_recipe_within(
                    conn, ligne, dossier, report, apply=apply)
            _import_ingredients_within(conn, grocy, recipe_ids, report,
                                       apply=apply)
            _import_meal_plan_within(conn, grocy, recipe_ids, report,
                                     today=today or _today(), apply=apply)
            if not apply:
                conn.rollback()
    finally:
        grocy.close()
    return report
